### ISSUE TITLE
Wish: Add the instructions somewhere visible

### ISSUE THREAD

**Issue by olpeh** [mkrl/screamforpapers#13]
Hey, tried using this, but after adding the repository, it does not find any suitable talk proposals in that repo.

However, there's no way to go back to seeing the initial instructions. Was there some kind of specific folder or something needed for the talks? 

Or is there a bug perhaps?

**Comment by olpeh** [comment]
Or maybe an example repository structure instead of just the example gist?

**Comment by olpeh** [comment]
My issue seems to have been that my file did not have .md in the name. Fixed now, but my wish about having the instructions somewhere is still valid.

**Comment by mkrl** [comment]
Valid point! As somewhat of a hack, you can retrigger onboarding by going to the dashboard and adding `?welcome` to the URL.

I think it would be nice to be able to trigger it manually from the dashboard, I'll leave this issue as a discussion point for that.

**Comment by mkrl** [comment]
Added a button to retrigger the onboarding tour from the settings in https://github.com/mkrl/screamforpapers/commit/8ee00406597c5bf002addce2342ce94aed6220b2

This will be published in the next Chrome Web Store release eventually, probably some time next week
